### PR TITLE
Initial fully working engine

### PR DESCRIPTION
**Pull request by mfish33**

### CODE REVIEW

**Comment by reddyalready** [comment]
@aurbano You're probably more familiar with rust at this point, mind taking a look?

**Comment by aurbano** [comment]
Last rust I wrote was 5 years ago so we're probably just as familiar 😂 

@mfish33 I'll trust you on this one!

**Review by aurbano — APPROVED** [review]

**Comment by mfish33** [comment]
Is this good to go?

I also think it is worth mentioning that this changes the way that the consumer is intended to use this. Previously this library was designed to be imported into a cargo.toml while with this PR, the repo is meant to be cloned and used as a base. The advantage of this is that it allows teams to peek into the game engine and modify it as they see fit. The reason I think that this is important is that once a team uses a low-level language like Rust, they are looking at any way possible to make their algorithm more efficient.

**Comment by reddyalready** [comment]
Happy with that approach, we only separate the agent in the JS projects because we need the server to be able to verify moves without being aware of players and vice versa.

I'll merge this now, but I've also added you as a maintainer to the repo so you're not blocked in the future. Happy to review any future PRs, to be clear.

Thanks for your contribution!

**Pull request merged**
